version: '2'
services:

  schema-registry:
    image: confluentinc/cp-schema-registry
    restart: always
    depends_on:
      - zookeeper
    container_name: schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
    ports:
      - 8085:8085
      
  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.3.0
    ports:
      - 8082:8082
    depends_on:
        - broker
        - zookeeper
        - schema-registry
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_BOOTSTRAP_SERVERS: "broker:29092"
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://localhost:8085"
      KAFKA_REST_DEBUG: "true"



